doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    all_or_nothing: true
    transactional: true
    check_database_platform: true
    organize_migrations: none
