<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\InternalLinkRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InternalLinkRepository::class)]
#[ORM\Table(name: 'internal_links')]
#[ORM\UniqueConstraint(name: 'uniq_source_target', columns: ['source_article_id', 'target_article_id'])]
class InternalLink
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer', options: ['unsigned' => true])]
    private int $id;

    #[ORM\ManyToOne(targetEntity: Article::class)]
    #[ORM\JoinColumn(name: 'source_article_id', nullable: false, onDelete: 'CASCADE')]
    private Article $sourceArticle;

    #[ORM\ManyToOne(targetEntity: Article::class)]
    #[ORM\JoinColumn(name: 'target_article_id', nullable: false, onDelete: 'CASCADE')]
    private Article $targetArticle;

    #[ORM\Column(length: 255)]
    private string $anchorText;

    #[ORM\Column(options: ['default' => false])]
    private bool $isAutoGenerated = false;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getSourceArticle(): Article
    {
        return $this->sourceArticle;
    }

    public function setSourceArticle(Article $sourceArticle): static
    {
        $this->sourceArticle = $sourceArticle;

        return $this;
    }

    public function getTargetArticle(): Article
    {
        return $this->targetArticle;
    }

    public function setTargetArticle(Article $targetArticle): static
    {
        $this->targetArticle = $targetArticle;

        return $this;
    }

    public function getAnchorText(): string
    {
        return $this->anchorText;
    }

    public function setAnchorText(string $anchorText): static
    {
        $this->anchorText = $anchorText;

        return $this;
    }

    public function isAutoGenerated(): bool
    {
        return $this->isAutoGenerated;
    }

    public function setIsAutoGenerated(bool $isAutoGenerated): static
    {
        $this->isAutoGenerated = $isAutoGenerated;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }
}
